### ISSUE TITLE
Quadratic time to gather tokens

### ISSUE THREAD

**Issue by lukeu** [mike-lischke/antlr4-c3#18] opened 2018-09-28 10:02 UTC
While profiling the performance of a port of this code, I found the following line dominated:

https://github.com/mike-lischke/antlr4-c3/blob/4f62e87dee69ab6d2a5f9d94dbb7c1fd9d3f310f/src/CodeCompletionCore.ts#L112

(In the Java antlr library at least...) LT performs a linear search from the 'seek' location, making this `O(N^2)` in the number of tokens gathered.

Would it work to call `LT(1)` each time, with `tokenStream.consume` at the end of the loop (after the `break`)?

**Comment by mike-lischke** [comment] 2018-09-28 12:31
Surprising that this call stands out, but I'm afraid you won't be able to optimize it out. This is a one-time loop to get all tokens from the start index up to the given position.

And it's also not quadratice in complexity. Look at [the LT() function](https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/CommonTokenStream.java#L90) where you can see it is calling `nextTokenOnChannel` for all tokens that are not yet loaded. However, the caching of the tokens is a loop counting up in steps of one, it will trigger `nextTokenOnChannel` exactly once for each token. And since there is no other loop involved this is actually O(n).

**Comment by lukeu** [comment] 2018-09-28 14:38
Thanks for the reference. If I read it correctly it's about the same as the Java version, and the token stream needs to be "externally advanced".  Took me a while to spot it too. 

I was seeing values of `k` being passed in of 60,000 whereas the member `p` remains 0, so the `while` loop inside does work repeatedly. (Giving me times like 13 s instead of 20 ms)

I fixed my own code with something like this:

        while (true) {
            let token = tokenStream.LT(1);
            this.tokens.push(token.type);
            if (token.tokenIndex >= caretTokenIndex || token.type == Token.EOF)
                break;
            tokenStream.comsume
        }
        tokenStream.seek(currentIndex);
 
(Sorry I don't know type-script, otherwise I would have made it a PR):

**Comment by mike-lischke** [comment] 2018-09-29 18:06
I see what you mean and I stand corrected. Of course, LT() doesn't advance the current token index. But instead of calling `consume` in the loop one could call `fetch()` on the underlying `BufferedTokenStream` with the caret token index and then in the loop use `get()` to retrieve the individual tokens. `fetch()` will be fast if the token stream has been filled at least until the caret token (which should be the case if you use your error check parser).

**Comment by omurbekjk** [comment] 2019-02-26 09:32
@lukeu Where did you add your code? maybe I will make pr for typescript version

**Comment by lukeu** [comment] 2019-02-27 12:13
> @lukeu Where did you add your code? maybe I will make pr for typescript version

To a private Scala port of the typescript code:
```
  private lazy val tokens: Vector[Token] = {
    var eof = false
    val result: ArrayBuffer[Token] = new ArrayBuffer()
    val tokStream = parser.getInputStream()
    val currentIndex = tokStream.index
    while (!eof) {
      val token = tokStream.LT(1)
      eof = caretTokenIndex.exists(_ <= token.getTokenIndex()) || token.getType() == Token.EOF
      if (!eof) {
        tokStream.consume()
        result += token
      }
    }
    tokStream.seek(if (currentIndex < 0) 0 else currentIndex)
    result.toVector
  }
```

Note the whole thing essentially obsolete by the official Java port anyway. (Which we would like to switch to & contribute back to next time this area of our code gets attention.)

Anyway, it should just be a matter of changing these lines:

https://github.com/mike-lischke/antlr4-c3/blob/4f62e87dee69ab6d2a5f9d94dbb7c1fd9d3f310f/src/CodeCompletionCore.ts#L111-L117

to something like my attempt at TS in my 2nd comment, taking into account Mike's reply (which I didn't succeed in applying to the Scala code).

**Comment by mike-lischke** [comment] 2020-12-23 10:26
It took quite some time, but I finally found the time to look at this problem. The solution is pretty simple: instead of using `LT` we can use the simple token `get` function. Would be good to get some feedback from you, if the issue is also fixed for you.

**Comment by moimael** [comment] 2021-01-13 21:00
This fix seems to change the behaviour of a bug we were having were 2 suggestions were displayed, but one of them was wrong. Now there is only one displayed, unfortunately, it's the wrong one.

**Comment by mike-lischke** [comment] 2021-03-10 14:20
@moimael I pushed a fix for a problem of the previous token retrieval optimization. Please check again if that solves your problem finally.

**Closed** 2021-09-04 08:49 UTC
Labels: bug
